version: '3'

services:
  client:
    build:
      context: ./Client
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
  server:
    build:
      context: ./Server
      dockerfile: Dockerfile
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN}
    ports:
      - "3000:3000"