version: '3'

services:
  client:
    build:
      context: ./Client
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
  server:
    build:
      context: ./Server
      dockerfile: Dockerfile
    ports:
      - "3000:3000"