version: '3'

services:
  client:
    build:
      context: ./Client
      dockerfile: Dockerfile
    image: spondzyk/tic-tac-toe-app-client:latest
    ports:
      - "8080:8080"

  server:
    build:
      context: ./Server
      dockerfile: Dockerfile
    image: spondzyk/tic-tac-toe-app-server:latest
    environment:
      FRONTEND_URL: cb-load-balancer-71054534.us-east-1.elb.amazonaws.com
    ports:
      - "3000:3000"